# Generated by Django 5.1 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_am', models.CharField(max_length=255, verbose_name='Name (Amharic)')),
                ('date_received', models.DateField(verbose_name='Date Received')),
                ('awarding_body_en', models.CharField(max_length=255, verbose_name='Awarding Body (English)')),
                ('awarding_body_am', models.CharField(max_length=255, verbose_name='Awarding Body (Amharic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_am', models.TextField(verbose_name='Description (Amharic)')),
                ('photo', models.ImageField(upload_to='awards/')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_am', models.CharField(max_length=255, verbose_name='Name (Amharic)')),
                ('date_issued', models.DateField(verbose_name='Date Issued')),
                ('issuing_organization_en', models.CharField(max_length=255, verbose_name='Issuing Organization (English)')),
                ('issuing_organization_am', models.CharField(max_length=255, verbose_name='Issuing Organization (Amharic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_am', models.TextField(verbose_name='Description (Amharic)')),
                ('photo', models.ImageField(upload_to='certificates/')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
    ]
