# Generated by Django 5.1 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_am', models.CharField(max_length=255, verbose_name='Title (Amharic)')),
                ('location_en', models.CharField(max_length=255, verbose_name='Location (English) ')),
                ('location_am', models.CharField(max_length=255, verbose_name='Location (Amharic)')),
                ('type', models.CharField(max_length=50)),
                ('posted', models.DateField()),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_am', models.TextField(verbose_name='Description (Amharic)')),
                ('details_en', models.TextField(verbose_name='Details (English)')),
                ('details_am', models.TextField(verbose_name='Details (Amharic)')),
            ],
            options={
                'ordering': ['title_en'],
            },
        ),
    ]
