# Generated by Django 5.1 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_am', models.CharField(max_length=255, verbose_name='Name (Amharic)')),
                ('role_en', models.CharField(max_length=255, verbose_name='Role (English)')),
                ('role_am', models.CharField(max_length=255, verbose_name='Role (Amharic)')),
                ('quote_en', models.TextField(verbose_name='Quote (English)')),
                ('quote_am', models.TextField(verbose_name='Quote (Amharic)')),
                ('photo', models.ImageField(upload_to='testimonials/')),
            ],
        ),
    ]
