# Generated by Django 5.1 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('saving_account', models.CharField(max_length=50, verbose_name='Saving Account')),
                ('loan_account', models.CharField(max_length=50, verbose_name='Loan Account')),
                ('receipt', models.FileField(upload_to='receipts/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
