# Generated by Django 5.1 on 2024-11-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_am', models.CharField(max_length=255, verbose_name='Name (Amharic)')),
            ],
        ),
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_am', models.CharField(max_length=255, verbose_name='Name (Amharic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_am', models.CharField(max_length=255, verbose_name='Title (Amharic)')),
                ('image', models.ImageField(upload_to='leadership/')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='leadership.committee')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
    ]
