# Generated by Django 5.1 on 2024-11-07 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_am', models.CharField(max_length=255, verbose_name='Title (Amharic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_am', models.TextField(verbose_name='Description (Amharic)')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['title_en'],
            },
        ),
    ]
