# Generated by Django 5.1 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.CharField(max_length=255, verbose_name='Question (English)')),
                ('question_am', models.CharField(max_length=255, verbose_name='Question (Amharic)')),
                ('answer_en', models.TextField(verbose_name='Answer (English)')),
                ('answer_am', models.TextField(verbose_name='Answer (Amharic)')),
            ],
            options={
                'ordering': ['question_en'],
            },
        ),
    ]
