# Generated by Django 5.1 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='Department Name (English)')),
                ('name_am', models.CharField(max_length=100, unique=True, verbose_name='Department Name (Amharic)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_am', models.TextField(verbose_name='Description (Amharic)')),
                ('image', models.ImageField(upload_to='department_images/')),
                ('head_name_en', models.CharField(max_length=100, verbose_name='Head Name (English)')),
                ('head_name_am', models.CharField(max_length=100, verbose_name='Head Name (Amharic)')),
                ('head_email', models.EmailField(max_length=254)),
                ('head_image', models.ImageField(upload_to='department_head_images/')),
            ],
        ),
    ]
